[package]
name = "create-socket"
version = "0.1.0"
authors = ["Christos KK Loverdos <loverdos@gmail.com>"]
edition = "2018"
keywords = ["unix", "domain", "socket"]
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

